### PR TITLE
Updates to pushkin cli

### PR DESCRIPTION
**Pull request by jkhartshorne**
* Removed node_modules and added .gitignore. That will speed up download. 
* Everywhere with a package.json, I deleted package-lock.json, ran `yarn install --latest`, and commited yarn.lock.

I'm not sure if that fixed the issues I was initially having on installing (I was using the wrong cli version), but it should improve installation.

You may want to do the same with the other templates.

Note that I haven't actually tried the template yet. I don't know if it works, only that it installs!

### CODE REVIEW

**Comment by jkhartshorne** [comment]
@conbainbridge thoughts?

**Comment by conbainbridge** [comment]
Oh, I've gone in and made some edits that fixes everything!

**Comment by jkhartshorne** [comment]
@conbainbridge - recommend that you at least use the .gitignore from this pull request. Reopening just to put it back in the queue.

**Comment by conbainbridge** [comment]
Not sure how to best weed through this pull request to confirm nothing will break (with several thousand files "changed" can't review easily), so I'm committing this independently of the pull request, and ensuring each exp template has this update.

**Comment by conbainbridge** [comment]
Done, as described above (to each exp template, manually from my own repos to streamline and keep neat), closing this for now again unless it makes sense to reopen!

**Pull request closed without merging**
