### PR TITLE
Upgrade to jsPsych 7

### PR DESCRIPTION
**Pull request by jessestorbeck**
Similar deal as pushkin-consortium/pushkin-exptemplates-lexical#4, the template has been overhauled based on the new jsPsych7-compatible basic experiment template (pushkin-consortium/pushkin-exptemplates-basic#39). I also tried to clean up the experiment code some and made some subtle changes that I deemed more realistic for a grammaticality judgment task (e.g. you probably wouldn't ask the same participant to judge grammatical and ungrammatical versions of the same sentence). But it still works in essentially the same way as before, and the same options exist in the config.js file.

One thing I haven't figured out is how to move the fixation cross into the center of the screen, or at least have it display in the same place as the item. It could be done in hacky ways like adding linebreaks, but a better solution might involve some changes to the CSS properties of the jsPsychTarget div.

### CODE REVIEW

**Comment by jkhartshorne** [comment]
@ayang21 -- you want to look into the fixation issue? I recommend posting a question in the discussion at https://github.com/jspsych/jsPsych

**Comment by jessestorbeck** [comment]
@jkhartshorne @ayang21 I think it's a Pushkin thing rather than a jsPsych thing, since it behaves as expected as a plain jsPsych experiment:
Screen Shot 2023-08-09 at 12 21 26 PM
Screen Shot 2023-08-09 at 12 22 33 PM
As a jsPsych experiment, the content is always vertically centered, but in Pushkin it is anchored to the top like this:
Screen Shot 2023-08-09 at 12 21 38 PM
Screen Shot 2023-08-09 at 12 22 15 PM

**Review by jkhartshorne — CHANGES_REQUESTED** [review]
@jessestorbeck -- please make the following change:

* Upgrade pushkin-client and pushkin-api, making sure they work
* Switch to using on_data_update rather than setSaveAfterEveryStimulus
* Revise the documentation for this template (or make a separate issue for that and assign it to someone).

**Comment by jkhartshorne** [comment]
@jessestorbeck, just a reminder.

> @jessestorbeck -- please make the following change:
> 
> * Upgrade pushkin-client and pushkin-api, making sure they work
> * Switch to using on_data_update rather than setSaveAfterEveryStimulus
> * Revise the documentation for this template (or make a separate issue for that and assign it to someone).

**Comment by jessestorbeck** [comment]
@jkhartshorne -- The plan for this template and the lexical decision template was to redo them based on the updates to the basic experiment template (https://github.com/pushkin-consortium/pushkin-exptemplates-basic/pull/45). I was waiting to do that until that PR for the basic template was merged (which in turn requires publishing new versions of the client and api).

That should handle:
> Upgrade pushkin-client and pushkin-api, making sure they work
> Switch to using on_data_update rather than setSaveAfterEveryStimulus

What changes to the docs are needed that weren't addressed by merging this PR? https://github.com/pushkin-consortium/pushkin/pull/235

**Comment by jessestorbeck** [comment]
@ayang21 @ellissc -- Likewise, this one can be tested with https://github.com/pushkin-consortium/pushkin-exptemplates-lexical/pull/5 (you could add a few of each to the same site to play with the config options). Docs are [here](https://languagelearninglab.gitbook.io/pushkin/advanced/modifying-experiment-templates/grammaticality-judgment-template).

**Pull request merged**
